package bookmark

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"bookmark/internal/adapters/shell"
	"bookmark/internal/domain"
)

var (
	ErrBookmarkNotFound = errors.New("bookmark not found")
	ErrInvalidAlias     = errors.New("invalid alias: must contain only alphanumeric characters, hyphens, and underscores")
)

// Manager handles bookmark CRUD operations.
type Manager struct {
	filePath         string
	shell            string
	navTool          string
	editor           string
	functionAlias    string
	interactiveAlias string
	shellAdapter     *shell.Adapter
}

// NewManager creates a new bookmark manager.
func NewManager(filePath string, shellType string, navTool string, editorCmd string, functionAlias string, interactiveAlias string) *Manager {
	return &Manager{
		filePath:         expandPath(filePath),
		shell:            shellType,
		navTool:          navTool,
		editor:           editorCmd,
		functionAlias:    functionAlias,
		interactiveAlias: interactiveAlias,
		shellAdapter:     shell.New(shellType),
	}
}

// Load reads all bookmarks from the shell script file.
func (m *Manager) Load() ([]domain.Bookmark, error) {
	if _, err := os.Stat(m.filePath); os.IsNotExist(err) {
		return []domain.Bookmark{}, nil
	}

	data, err := os.ReadFile(m.filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read bookmark file: %w", err)
	}

	return m.parseShellScript(string(data))
}

// parseShellScript extracts bookmarks from shell script with embedded metadata.
func (m *Manager) parseShellScript(content string) ([]domain.Bookmark, error) {
	var bookmarks []domain.Bookmark
	var currentBookmark *domain.Bookmark

	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and header comments
		if line == "" || strings.HasPrefix(line, "# Generated") || strings.HasPrefix(line, "# Do not") {
			continue
		}

		// Parse metadata comments
		if strings.HasPrefix(line, "# BM:") {
			if currentBookmark != nil {
				bookmarks = append(bookmarks, *currentBookmark)
			}
			currentBookmark = &domain.Bookmark{}

			// Parse metadata: # BM: alias|path|desc|created|updated|tmux|execute|postscript|file
			parts := strings.Split(strings.TrimPrefix(line, "# BM: "), "|")
			if len(parts) >= 2 {
				currentBookmark.Alias = parts[0]
				currentBookmark.Path = parts[1]
			}
			if len(parts) >= 3 {
				currentBookmark.Description = parts[2]
			}
			if len(parts) >= 4 && parts[3] != "" {
				currentBookmark.CreatedAt, _ = time.Parse(time.RFC3339, parts[3])
			}
			if len(parts) >= 5 && parts[4] != "" {
				currentBookmark.UpdatedAt, _ = time.Parse(time.RFC3339, parts[4])
			}
			if len(parts) >= 6 {
				currentBookmark.TmuxWindowName = parts[5]
			}
			if len(parts) >= 7 {
				currentBookmark.Execute = parts[6]
			}
			if len(parts) >= 8 {
				currentBookmark.PostJumpScript = parts[7]
			}
			if len(parts) >= 9 {
				currentBookmark.File = parts[8]
			}
		}
	}

	// Add last bookmark
	if currentBookmark != nil {
		bookmarks = append(bookmarks, *currentBookmark)
	}

	return bookmarks, scanner.Err()
}

// Save writes all bookmarks to the shell script file.
func (m *Manager) Save(bookmarks []domain.Bookmark) error {
	if err := os.MkdirAll(filepath.Dir(m.filePath), 0o755); err != nil {
		return fmt.Errorf("failed to create bookmark directory: %w", err)
	}

	return m.generateShellScript(bookmarks)
}

// generateShellScript creates shell aliases with embedded metadata.
func (m *Manager) generateShellScript(bookmarks []domain.Bookmark) error {
	var script strings.Builder

	script.WriteString("# Generated by bookmark manager\n")
	script.WriteString("# Do not edit manually - changes will be overwritten\n\n")

	// Add function wrapper if enabled
	if m.functionAlias != "" && m.functionAlias != "false" {
		functionName := "bookmark"
		if m.functionAlias != "true" {
			functionName = m.functionAlias
		}

		script.WriteString(m.generateFunctionWrapper(functionName))
		script.WriteString("\n")
	}

	// Add interactive alias wrapper if enabled
	if m.interactiveAlias != "" && m.interactiveAlias != "false" {
		script.WriteString(m.generateInteractiveWrapper(m.interactiveAlias))
		script.WriteString("\n")
	}

	for _, bm := range bookmarks {
		// Write metadata as comment
		metadata := fmt.Sprintf("# BM: %s|%s|%s|%s|%s|%s|%s|%s|%s\n",
			bm.Alias,
			bm.Path,
			bm.Description,
			bm.CreatedAt.Format(time.RFC3339),
			bm.UpdatedAt.Format(time.RFC3339),
			bm.TmuxWindowName,
			bm.Execute,
			bm.PostJumpScript,
			bm.File,
		)
		script.WriteString(metadata)

		// Write shell alias/function using adapter
		cmd := m.BuildNavigationCommand(bm)
		aliasStr := m.shellAdapter.FormatAlias(bm.Alias, cmd)
		script.WriteString(aliasStr)
	}

	return os.WriteFile(m.filePath, []byte(script.String()), 0o644)
}

// generateFunctionWrapper creates a shell function that wraps the bookmark command
// and auto-sources the bookmarks file after execution.
func (m *Manager) generateFunctionWrapper(functionName string) string {
	var wrapper strings.Builder

	wrapper.WriteString("# Function wrapper to auto-source bookmarks after running bookmark commands\n")
	wrapper.WriteString("# This ensures new/updated bookmarks are immediately available in your shell\n")

	switch m.shell {
	case "fish":
		wrapper.WriteString(fmt.Sprintf("function %s\n", functionName))
		wrapper.WriteString(fmt.Sprintf("\tcommand %s $argv; and source %s\n", functionName, m.filePath))
		wrapper.WriteString("end\n")
	case "nu", "nushell":
		// Nushell doesn't support this pattern well, skip wrapper
		wrapper.WriteString(fmt.Sprintf("# Note: Nushell doesn't support function wrappers. Please source %s manually after updates.\n", m.filePath))
	default: // bash, zsh, sh
		wrapper.WriteString(fmt.Sprintf("%s() {\n", functionName))
		wrapper.WriteString(fmt.Sprintf("\tcommand %s \"$@\" && source %s\n", functionName, m.filePath))
		wrapper.WriteString("}\n")
	}

	return wrapper.String()
}

// generateInteractiveWrapper creates a shell function for interactive bookmark navigation.
// This function runs 'bookmark -i' and executes the selected bookmark command.
func (m *Manager) generateInteractiveWrapper(functionName string) string {
	var wrapper strings.Builder

	wrapper.WriteString("# Interactive bookmark navigation function\n")
	wrapper.WriteString("# Displays the TUI and executes the selected bookmark command\n")

	switch m.shell {
	case "fish":
		wrapper.WriteString(fmt.Sprintf("function %s\n", functionName))
		wrapper.WriteString("\tset -x CLICOLOR_FORCE 1\n")
		wrapper.WriteString("\tset cmd (bookmark -i)\n")
		wrapper.WriteString("\tif test -n \"$cmd\"\n")
		wrapper.WriteString("\t\teval $cmd\n")
		wrapper.WriteString("\tend\n")
		wrapper.WriteString("end\n")
	case "nu", "nushell":
		wrapper.WriteString(fmt.Sprintf("# Note: Nushell interactive wrapper\n"))
		wrapper.WriteString(fmt.Sprintf("def %s [] {\n", functionName))
		wrapper.WriteString("\twith-env {CLICOLOR_FORCE: \"1\"} {\n")
		wrapper.WriteString("\t\tlet cmd = (bookmark -i)\n")
		wrapper.WriteString("\t\tif ($cmd | is-not-empty) {\n")
		wrapper.WriteString("\t\t\tnu -c $cmd\n")
		wrapper.WriteString("\t\t}\n")
		wrapper.WriteString("\t}\n")
		wrapper.WriteString("}\n")
	default: // bash, zsh, sh
		wrapper.WriteString(fmt.Sprintf("%s() {\n", functionName))
		wrapper.WriteString("\tlocal cmd=$(CLICOLOR_FORCE=1 bookmark -i)\n")
		wrapper.WriteString("\tif [[ -n \"$cmd\" ]]; then\n")
		wrapper.WriteString("\t\teval \"$cmd\"\n")
		wrapper.WriteString("\tfi\n")
		wrapper.WriteString("}\n")
	}

	return wrapper.String()
}

// BuildNavigationCommand constructs the full command for a bookmark.
// Order: navigate → tmux rename → execute → post-jump → open file
func (m *Manager) BuildNavigationCommand(bm domain.Bookmark) string {
	var parts []string

	// 1. Navigation command (always first)
	navCmd := "cd"
	if m.navTool != "" && m.navTool != "none" {
		navCmd = m.navTool
	}
	parts = append(parts, fmt.Sprintf("%s '%s'", navCmd, bm.Path))

	// 2. Tmux window rename (after navigation)
	if bm.TmuxWindowName != "" {
		parts = append(parts, fmt.Sprintf("tmux rename-window '%s'", bm.TmuxWindowName))
	}

	// 3. Execute command
	if bm.Execute != "" {
		parts = append(parts, bm.Execute)
	}

	// 4. Post-jump script
	if bm.PostJumpScript != "" {
		parts = append(parts, bm.PostJumpScript)
	}

	// 5. Open file in editor (always last)
	if bm.File != "" && m.editor != "" {
		parts = append(parts, fmt.Sprintf("%s '%s'", m.editor, bm.File))
	}

	return strings.Join(parts, " && ")
}

// Add creates or updates a bookmark.
func (m *Manager) Add(bookmark domain.Bookmark) error {
	if !isValidAlias(bookmark.Alias) {
		return ErrInvalidAlias
	}

	bookmarks, err := m.Load()
	if err != nil {
		return err
	}

	now := time.Now()
	bookmark.UpdatedAt = now

	// Check if bookmark exists
	found := false
	for i, b := range bookmarks {
		if b.Alias == bookmark.Alias {
			bookmark.CreatedAt = b.CreatedAt
			bookmarks[i] = bookmark
			found = true
			break
		}
	}

	if !found {
		bookmark.CreatedAt = now
		bookmarks = append(bookmarks, bookmark)
	}

	return m.Save(bookmarks)
}

// Get retrieves a bookmark by alias.
func (m *Manager) Get(alias string) (domain.Bookmark, error) {
	bookmarks, err := m.Load()
	if err != nil {
		return domain.Bookmark{}, err
	}

	for _, b := range bookmarks {
		if b.Alias == alias {
			return b, nil
		}
	}

	return domain.Bookmark{}, ErrBookmarkNotFound
}

// Delete removes a bookmark by alias.
func (m *Manager) Delete(alias string) error {
	bookmarks, err := m.Load()
	if err != nil {
		return err
	}

	found := false
	filtered := make([]domain.Bookmark, 0, len(bookmarks))
	for _, b := range bookmarks {
		if b.Alias != alias {
			filtered = append(filtered, b)
		} else {
			found = true
		}
	}

	if !found {
		return ErrBookmarkNotFound
	}

	return m.Save(filtered)
}

// Exists checks if a bookmark with the given alias exists.
func (m *Manager) Exists(alias string) (bool, error) {
	_, err := m.Get(alias)
	if err == ErrBookmarkNotFound {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

// GenerateAlias creates an alias from a directory path.
func GenerateAlias(path string, separator string, lowercase bool) string {
	base := filepath.Base(path)

	// Split on common separators
	parts := strings.FieldsFunc(base, func(r rune) bool {
		return r == '-' || r == '_' || r == ' ' || r == '.'
	})

	if len(parts) == 0 {
		return "bm"
	}

	// Take first letter of each part
	var alias strings.Builder
	for i, part := range parts {
		if len(part) > 0 {
			if i > 0 && separator != "" {
				alias.WriteString(separator)
			}
			firstChar := string(part[0])
			if lowercase {
				firstChar = strings.ToLower(firstChar)
			} else {
				firstChar = strings.ToUpper(firstChar)
			}
			alias.WriteString(firstChar)
		}
	}

	return alias.String()
}

func isValidAlias(alias string) bool {
	if alias == "" {
		return false
	}
	for _, r := range alias {
		if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '_' || r == '-') {
			return false
		}
	}
	return true
}

func expandPath(path string) string {
	if path == "" {
		return path
	}
	if strings.HasPrefix(path, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, path[2:])
		}
	}
	return os.ExpandEnv(path)
}

// FindBookmarkLine returns the line number where a bookmark alias is defined in the shell script.
func (m *Manager) FindBookmarkLine(alias string) (int, error) {
	data, err := os.ReadFile(m.filePath)
	if err != nil {
		return 0, fmt.Errorf("failed to read bookmark file: %w", err)
	}

	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	lineNum := 0
	foundMetadata := false

	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())

		// Look for the bookmark metadata comment first
		if strings.HasPrefix(line, "# BM:") {
			parts := strings.Split(strings.TrimPrefix(line, "# BM: "), "|")
			if len(parts) > 0 && parts[0] == alias {
				foundMetadata = true
				continue
			}
		}

		// If we found the metadata, the next non-empty line should be the alias/function
		if foundMetadata && line != "" {
			// Check if this line contains the alias definition
			if m.shell == "fish" {
				if strings.HasPrefix(line, "function "+alias) {
					return lineNum, nil
				}
			} else {
				if strings.HasPrefix(line, "alias "+alias+"=") {
					return lineNum, nil
				}
			}
		}
	}

	return 0, ErrBookmarkNotFound
}
